import React from 'react';
import Pod from 'utility/components.js';
import PureRender from 'utility/pureRender.js';

module.exports = class IconExample extends React.Component {

    shouldComponentUpdate = PureRender;

    render() {
        return (
            <div>
                <Pod.ContentWrap>
                    <span style={{ fontSize: '30px' }}>
                        <Pod.Icon>home</Pod.Icon>&nbsp;
                        <Pod.Icon styler={{ color: '#07ADD4', size: '10rem' }}>assessment</Pod.Icon>&nbsp;
                        <Pod.Icon styler={{ color: '#3F70E2' }}>polymer</Pod.Icon>&nbsp;
                        <Pod.Icon styler={{ color: '#D53FD6' }}>question_answer</Pod.Icon>&nbsp;
                        <Pod.Icon styler={{ color: '#FF6044' }}>whatshot</Pod.Icon>

                        <br /><br />

                        <Pod.Icon>info_outline</Pod.Icon>
                        <Pod.Icon>input</Pod.Icon>
                        <Pod.Icon>invert_colors</Pod.Icon>
                        <Pod.Icon>label</Pod.Icon>
                        <Pod.Icon>label_outline</Pod.Icon>
                        <Pod.Icon>language</Pod.Icon>
                        <Pod.Icon>query_builder</Pod.Icon>
                        <Pod.Icon>perm_identity</Pod.Icon>
                        <Pod.Icon>perm_media</Pod.Icon>
                        <Pod.Icon>perm_phone_msg</Pod.Icon>
                        <Pod.Icon>perm_scan_wifi</Pod.Icon>
                        <Pod.Icon>picture_in_picture</Pod.Icon>
                        <Pod.Icon>play_for_work</Pod.Icon>
                        <Pod.Icon>polymer</Pod.Icon>
                        <Pod.Icon>power_settings_new</Pod.Icon>
                        <Pod.Icon>print</Pod.Icon>
                        <Pod.Icon>thumb_down</Pod.Icon>
                        <Pod.Icon>thumb_up</Pod.Icon>
                        <Pod.Icon>thumbs_up_down</Pod.Icon>
                        <Pod.Icon>email</Pod.Icon>
                        <Pod.Icon>dialpad</Pod.Icon>
                        <Pod.Icon>dialer_sip</Pod.Icon>
                        <Pod.Icon>contacts</Pod.Icon>
                        <Pod.Icon>forward_5</Pod.Icon>
                        <Pod.Icon>stay_current_portrait</Pod.Icon>
                        <Pod.Icon>stay_primary_landscape</Pod.Icon>
                        <Pod.Icon>stay_primary_portrait</Pod.Icon>
                        <Pod.Icon>swap_calls</Pod.Icon>
                        <Pod.Icon>textsms</Pod.Icon>
                        <Pod.Icon>voicemail</Pod.Icon>
                        <Pod.Icon>vpn_key</Pod.Icon>
                        <Pod.Icon>group_work</Pod.Icon>
                        <Pod.Icon>grade</Pod.Icon>
                        <Pod.Icon>clear_all</Pod.Icon>
                        <Pod.Icon>chat_bubble_outline</Pod.Icon>
                        <Pod.Icon>chat_bubble</Pod.Icon>
                        <Pod.Icon>repeat</Pod.Icon>
                        <Pod.Icon>repeat_one</Pod.Icon>
                        <Pod.Icon>replay</Pod.Icon>
                        <Pod.Icon>replay_10</Pod.Icon>
                        <Pod.Icon>replay_30</Pod.Icon>
                        <Pod.Icon>replay_5</Pod.Icon>
                        <Pod.Icon>shuffle</Pod.Icon>
                        <Pod.Icon>skip_next</Pod.Icon>
                        <Pod.Icon>skip_previous</Pod.Icon>
                        <Pod.Icon>contact_phone</Pod.Icon>
                        <Pod.Icon>comment</Pod.Icon>
                        <Pod.Icon>recent_actors</Pod.Icon>
                        <Pod.Icon>snooze</Pod.Icon>
                        <Pod.Icon>sort_by_alpha</Pod.Icon>
                        <Pod.Icon>stop</Pod.Icon>
                        <Pod.Icon>subtitles</Pod.Icon>
                        <Pod.Icon>surround_sound</Pod.Icon>
                        <Pod.Icon>web</Pod.Icon>
                        <Pod.Icon>volume_up</Pod.Icon>
                        <Pod.Icon>volume_off</Pod.Icon>
                        <Pod.Icon>volume_mute</Pod.Icon>
                        <Pod.Icon>toc</Pod.Icon>
                        <Pod.Icon>today</Pod.Icon>
                        <Pod.Icon>toll</Pod.Icon>
                        <Pod.Icon>track_changes</Pod.Icon>
                        <Pod.Icon>translate</Pod.Icon>
                        <Pod.Icon>trending_down</Pod.Icon>
                        <Pod.Icon>question_answer</Pod.Icon>
                        <Pod.Icon>receipt</Pod.Icon>
                        <Pod.Icon>done</Pod.Icon>
                        <Pod.Icon>tab</Pod.Icon>
                        <Pod.Icon>tab_unselected</Pod.Icon>
                        <Pod.Icon>theaters</Pod.Icon>
                        <Pod.Icon>hd</Pod.Icon>
                        <Pod.Icon>games</Pod.Icon>
                        <Pod.Icon>hearing</Pod.Icon>
                        <Pod.Icon>view_module</Pod.Icon>
                        <Pod.Icon>view_list</Pod.Icon>
                        <Pod.Icon>settings_remote</Pod.Icon>
                        <Pod.Icon>settings_voice</Pod.Icon>
                        <Pod.Icon>search</Pod.Icon>
                        <Pod.Icon>settings</Pod.Icon>
                        <Pod.Icon>settings_applications</Pod.Icon>
                        <Pod.Icon>settings_backup_restore</Pod.Icon>
                        <Pod.Icon>settings_bluetooth</Pod.Icon>
                        <Pod.Icon>settings_brightness</Pod.Icon>
                        <Pod.Icon>settings_cell</Pod.Icon>
                        <Pod.Icon>settings_ethernet</Pod.Icon>
                        <Pod.Icon>settings_input_antenna</Pod.Icon>
                        <Pod.Icon>trending_flat</Pod.Icon>
                        <Pod.Icon>trending_up</Pod.Icon>
                        <Pod.Icon>work</Pod.Icon>
                        <Pod.Icon>youtube_searched_for</Pod.Icon>
                        <Pod.Icon>zoom_in</Pod.Icon>
                        <Pod.Icon>my_location</Pod.Icon>
                        <Pod.Icon>visibility_off</Pod.Icon>
                        <Pod.Icon>visibility</Pod.Icon>
                        <Pod.Icon>view_week</Pod.Icon>
                        <Pod.Icon>view_stream</Pod.Icon>
                        <Pod.Icon>view_quilt</Pod.Icon>
                        <Pod.Icon>video_library</Pod.Icon>
                        <Pod.Icon>videocam</Pod.Icon>
                        <Pod.Icon>videocam_off</Pod.Icon>
                        <Pod.Icon>volume_down</Pod.Icon>
                        <Pod.Icon>settings_overscan</Pod.Icon>
                        <Pod.Icon>settings_input_svideo</Pod.Icon>
                        <Pod.Icon>settings_input_hdmi</Pod.Icon>
                        <Pod.Icon>settings_input_composite</Pod.Icon>
                        <Pod.Icon>settings_input_component</Pod.Icon>
                        <Pod.Icon>launch</Pod.Icon>
                        <Pod.Icon>perm_device_information</Pod.Icon>
                        <Pod.Icon>perm_data_setting</Pod.Icon>
                        <Pod.Icon>zoom_out</Pod.Icon>
                        <Pod.Icon>alarm_on</Pod.Icon>
                        <Pod.Icon>dns</Pod.Icon>
                        <Pod.Icon>redeem</Pod.Icon>
                        <Pod.Icon>reorder</Pod.Icon>
                        <Pod.Icon>report_problem</Pod.Icon>
                        <Pod.Icon>restore</Pod.Icon>
                        <Pod.Icon>room</Pod.Icon>
                        <Pod.Icon>schedule</Pod.Icon>
                        <Pod.Icon>movie</Pod.Icon>
                        <Pod.Icon>android</Pod.Icon>
                        <Pod.Icon>announcement</Pod.Icon>
                        <Pod.Icon>mic_off</Pod.Icon>
                        <Pod.Icon>mic_none</Pod.Icon>
                        <Pod.Icon>swap_horiz</Pod.Icon>
                        <Pod.Icon>swap_vert</Pod.Icon>
                        <Pod.Icon>swap_vertical_circle</Pod.Icon>
                        <Pod.Icon>system_update_alt</Pod.Icon>
                        <Pod.Icon>present_to_all</Pod.Icon>
                        <Pod.Icon>portable_wifi_off</Pod.Icon>
                        <Pod.Icon>phonelink_setup</Pod.Icon>
                        <Pod.Icon>phonelink_ring</Pod.Icon>
                        <Pod.Icon>phonelink_lock</Pod.Icon>
                        <Pod.Icon>phonelink_erase</Pod.Icon>
                        <Pod.Icon>person_pin</Pod.Icon>
                        <Pod.Icon>navigation</Pod.Icon>
                        <Pod.Icon>new_releases</Pod.Icon>
                        <Pod.Icon>not_interested</Pod.Icon>
                        <Pod.Icon>pause</Pod.Icon>
                        <Pod.Icon>pause_circle_filled</Pod.Icon>
                        <Pod.Icon>pause_circle_outline</Pod.Icon>
                        <Pod.Icon>play_arrow</Pod.Icon>
                        <Pod.Icon>play_circle_filled</Pod.Icon>
                        <Pod.Icon>play_circle_outline</Pod.Icon>
                        <Pod.Icon>playlist_add</Pod.Icon>
                        <Pod.Icon>queue</Pod.Icon>
                        <Pod.Icon>queue_music</Pod.Icon>
                        <Pod.Icon>radio</Pod.Icon>
                        <Pod.Icon>class</Pod.Icon>
                        <Pod.Icon>code</Pod.Icon>
                        <Pod.Icon>credit_card</Pod.Icon>
                        <Pod.Icon>dashboard</Pod.Icon>
                        <Pod.Icon>delete</Pod.Icon>
                        <Pod.Icon>description</Pod.Icon>
                        <Pod.Icon>open_with</Pod.Icon>
                        <Pod.Icon>pageview</Pod.Icon>
                        <Pod.Icon>payment</Pod.Icon>
                        <Pod.Icon>perm_camera_mic</Pod.Icon>
                        <Pod.Icon>perm_contact_calendar</Pod.Icon>
                        <Pod.Icon>airplay</Pod.Icon>
                        <Pod.Icon>done_all</Pod.Icon>
                        <Pod.Icon>phone</Pod.Icon>
                        <Pod.Icon>no_sim</Pod.Icon>
                        <Pod.Icon>invert_colors_off</Pod.Icon>
                        <Pod.Icon>chat</Pod.Icon>
                        <Pod.Icon>call_split</Pod.Icon>
                        <Pod.Icon>call_received</Pod.Icon>
                        <Pod.Icon>call_missed</Pod.Icon>
                        <Pod.Icon>call_merge</Pod.Icon>
                        <Pod.Icon>call_made</Pod.Icon>
                        <Pod.Icon>call_end</Pod.Icon>
                        <Pod.Icon>call</Pod.Icon>
                        <Pod.Icon>business</Pod.Icon>
                        <Pod.Icon>alarm_off</Pod.Icon>
                        <Pod.Icon>message</Pod.Icon>
                        <Pod.Icon>location_on</Pod.Icon>
                        <Pod.Icon>location_off</Pod.Icon>
                        <Pod.Icon>live_help</Pod.Icon>
                        <Pod.Icon>album</Pod.Icon>
                        <Pod.Icon>av_timer</Pod.Icon>
                        <Pod.Icon>closed_caption</Pod.Icon>
                        <Pod.Icon>equalizer</Pod.Icon>
                        <Pod.Icon>turned_in_not</Pod.Icon>
                        <Pod.Icon>verified_user</Pod.Icon>
                        <Pod.Icon>view_agenda</Pod.Icon>
                        <Pod.Icon>view_array</Pod.Icon>
                        <Pod.Icon>view_carousel</Pod.Icon>
                        <Pod.Icon>view_column</Pod.Icon>
                        <Pod.Icon>subject</Pod.Icon>
                        <Pod.Icon>supervisor_account</Pod.Icon>
                        <Pod.Icon>settings_power</Pod.Icon>
                        <Pod.Icon>shop</Pod.Icon>
                        <Pod.Icon>shop_two</Pod.Icon>
                        <Pod.Icon>shopping_basket</Pod.Icon>
                        <Pod.Icon>shopping_cart</Pod.Icon>
                        <Pod.Icon>speaker_notes</Pod.Icon>
                        <Pod.Icon>spellcheck</Pod.Icon>
                        <Pod.Icon>star_rate</Pod.Icon>
                        <Pod.Icon>stars</Pod.Icon>
                        <Pod.Icon>store</Pod.Icon>
                        <Pod.Icon>ring_volume</Pod.Icon>
                        <Pod.Icon>speaker_phone</Pod.Icon>
                        <Pod.Icon>stay_current_landscape</Pod.Icon>
                        <Pod.Icon>forum</Pod.Icon>
                        <Pod.Icon>import_export</Pod.Icon>
                        <Pod.Icon>open_in_browser</Pod.Icon>
                        <Pod.Icon>open_in_new</Pod.Icon>
                        <Pod.Icon>forward_30</Pod.Icon>
                        <Pod.Icon>turned_in</Pod.Icon>
                        <Pod.Icon>view_headline</Pod.Icon>
                        <Pod.Icon>view_day</Pod.Icon>
                        <Pod.Icon>warning</Pod.Icon>
                        <Pod.Icon>error_outline</Pod.Icon>
                        <Pod.Icon>error</Pod.Icon>
                        <Pod.Icon>add_alert</Pod.Icon>
                        <Pod.Icon>settings_phone</Pod.Icon>
                        <Pod.Icon>forward_10</Pod.Icon>
                        <Pod.Icon>fast_rewind</Pod.Icon>
                        <Pod.Icon>fast_forward</Pod.Icon>
                        <Pod.Icon>explicit</Pod.Icon>
                        <Pod.Icon>list</Pod.Icon>
                        <Pod.Icon>lock</Pod.Icon>
                        <Pod.Icon>lock_open</Pod.Icon>
                        <Pod.Icon>lock_outline</Pod.Icon>
                        <Pod.Icon>loyalty</Pod.Icon>
                        <Pod.Icon>markunread_mailbox</Pod.Icon>
                        <Pod.Icon>note_add</Pod.Icon>
                        <Pod.Icon>offline_pin</Pod.Icon>
                        <Pod.Icon>http</Pod.Icon>
                        <Pod.Icon>mic</Pod.Icon>
                        <Pod.Icon>loop</Pod.Icon>
                        <Pod.Icon>library_music</Pod.Icon>
                        <Pod.Icon>library_books</Pod.Icon>
                        <Pod.Icon>library_add</Pod.Icon>
                        <Pod.Icon>high_quality</Pod.Icon>
                        <Pod.Icon>info</Pod.Icon>
                        <Pod.Icon>https</Pod.Icon>
                        <Pod.Icon>aspect_ratio</Pod.Icon>
                        <Pod.Icon>assessment</Pod.Icon>
                        <Pod.Icon>assignment</Pod.Icon>
                        <Pod.Icon>assignment_ind</Pod.Icon>
                        <Pod.Icon>assignment_late</Pod.Icon>
                        <Pod.Icon>mode_edit</Pod.Icon>
                    </span>

                </Pod.ContentWrap>
            </div>
        );
    }
};
